/* dishes.js — elenco condiviso dei piatti predefiniti (usati per generare i piani
   e mostrati anche nella pagina del calendario). Incluso da index.html e piano_settimanale.html. */
const BASE_DISHES = [
  { name: "Pollo e patate", source: "Carne Bianca" },
  { name: "Branzino al forno", source: "Pesce" },
  { name: "Poke Salmone", source: "Pesce" },
  { name: "Poke Tonno", source: "Pesce" },
  { name: "Grigliata di tonno", source: "Pesce" },
  { name: "Udon gamberetti zucchine e carote", source: "Pesce" },
  { name: "Risotto frutti di mare", source: "Pesce" },
  { name: "Risotto gamberi", source: "Pesce" },
  { name: "Lupo di mare", source: "Pesce" },
  { name: "Salmone al forno con arancia", source: "Pesce" },
  { name: "Salmone con salsa norvegese", source: "Pesce" },
  { name: "Zuppa di lenticchie", source: "Legumi" },
  { name: "Pasta e fagioli", source: "Legumi" },
  { name: "Hummus", source: "Legumi" },
  { name: "Insalata di couscous/riso con legumi", source: "Legumi" },
  { name: "Polpette con legumi", source: "Legumi" },
  { name: "Falafel", source: "Legumi" },
  { name: "Pollo alle mandorle", source: "Carne Bianca" },
  { name: "Cosce di pollo al vino", source: "Carne Bianca" },
  { name: "Pollo speziato all'arancia", source: "Carne Bianca" },
  { name: "Pollo marinato", source: "Carne Bianca" },
  { name: "Pollo alla griglia", source: "Carne Bianca" },
  { name: "Pollo allo spiedo", source: "Carne Bianca" },
  { name: "Pollo al curry", source: "Carne Bianca" },
  { name: "Filetto alla griglia", source: "Carne Rossa" },
  { name: "Polpette al sugo", source: "Carne Rossa" },
  { name: "Hamburger", source: "Carne Rossa" },
  { name: "Insalata di farro con feta", source: "Latticini" },
  { name: "Polpettone veg e ricotta", source: "Latticini" },
  { name: "Pasta al pomodoro con parmigiano/grana", source: "Latticini" },
  { name: "Insalata melone e feta", source: "Latticini" },
  { name: "Frittata asparagi", source: "Uova" },
  { name: "Frittata porro e zucchine", source: "Uova" },
  { name: "Uova (generico)", source: "Uova" },
  { name: "Fattoush con crostini di pane", source: "Insalate" },
  { name: "Insalata di finocchio", source: "Insalate" },
  { name: "Insalata pomodoro e cipolla", source: "Insalate" },
  { name: "Piadina con affettati", source: "Affettati Magri" },
  { name: "Pizza", source: "Stella" },
  { name: "Sushi", source: "Stella" },
  { name: "Ristorante (libero)", source: "Stella" },
  { name: "Aperitivo Eataly", source: "Stella" },
];
